### ISSUE TITLE
arity calculations disallow prop7

### ISSUE THREAD

**Issue by kquick** [silentbicycle/theft#24]
THEFT_MAX_ARITY is defined as 7, which is used for allocation of the type_info, but creating a prop7 property function always fails because theft_run.c:infer_arity will return 0.

The infer_arity should probably return THEFT_MAX_ARITY instead of 0 when falling out of the loop, but whether type_info should be NULL terminated, or whether there are other locations with THEFT_MAX_ARITY issues is an open question.

**Comment by silentbicycle** [comment]
Good find, thanks. I recently reduced the max arity to 7 (it was 10), but I've never actually had reason to use an arity higher than 2. This got missed.

**Comment by silentbicycle** [comment]
Fixed by a8af8fe, will be in the next release.

**Comment by kquick** [comment]
Excellent, thank you.  It was a pretty unusual test that needed this arity level, but it is handy when you do need it.

**Comment by silentbicycle** [comment]
I'd love to hear more about how you're using theft! My contact info is in my profile.
