### ISSUE TITLE
Build on AIX problem

### ISSUE THREAD

**Issue by SharplEr** [silentbicycle/theft#3]
I try to build your code in AIX with GNU Make and GCC. So in AIX we have file type.h  with the line:

```C
typedef uint_t uint
```

And this leads to name conflict with your test_theft.c. I just renamd your "uint" to "uint_val" and it worked. So i mean will be better to rename "uint" to some more specific. I am reading your code about 1 minute and afraid to offer a specific name.

**Comment by silentbicycle** [comment]
That's good to know. I will rename the identifier so it's not an issue.
