### ISSUE TITLE
undefined reference to fmod

### ISSUE THREAD

**Issue by carlodicelico** [silentbicycle/theft#46]
Re-running tests now, but it seems there _might_ be an issue:

```shell
/usr/local/lib/libtheft.a(theft_aux_builtin.o): In function `double_alloc':
/home/pi/theft/src/theft_aux_builtin.c:181: undefined reference to `fmod'
/usr/local/lib/libtheft.a(theft_aux_builtin.o): In function `float_alloc':
/home/pi/theft/src/theft_aux_builtin.c:178: undefined reference to `fmodf'
collect2: error: ld returned 1 exit status
```
This is theft v0.4.5. System info: Linux raspberrypi 4.14.79-v7+ #1159 SMP armv7l GNU/Linux

Theft info:

pi@raspberrypi:~/theft $ sudo make install
install -d /usr/local/lib/
install -c build/libtheft.a /usr/local/lib/libtheft.a
install -d /usr/local/include/
install -c inc/theft.h /usr/local/include/
install -c inc/theft_types.h /usr/local/include/
install -d /usr/local/share/pkgconfig/
install -c -m 644 build/libtheft.pc /usr/local/share/pkgconfig/

**Comment by carlodicelico** [comment]
Tests pass, I think this is user error on my part—something about how I'm linking, no doubt. Closing.

**Comment by silentbicycle** [comment]
No problem, thanks for making the effort of reporting it.

Were you missing `#include <math.h>` or `-lm` in your linker flags?
